# golangci-lint run

linters:
  enable-all: true
  disable:
    # deprecated
    - deadcode
    - exhaustivestruct
    - ifshort
    - interfacer
    - scopelint
    - golint
    - maligned
    - nosnakecase
    - varcheck
    - structcheck

    # disabled
    - cyclop
    - exhaustruct # extract code bload
    - forbidigo # forbids the use for fmt.Print(f|ln)
    - nlreturn # opinionated
    - nonamedreturns # opinionated
    - paralleltest # causes tests to randomly fail
    - tagliatelle # my interfere with external apis?
    - varnamelen # too many false-pos.
    - wrapcheck # wrapping 3rd party errors such as those from bolt are unnecessary
    - wsl # whitespace linter, slow, aggressive and opinionated

    # generics
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign
#
# Fixes
# gofumpt -l -w <file> || <dir>/*
# gci write <dir>/*

# install tools
# gofumpt: go install mvdan.cc/gofumpt@latest
# gci: go install github.com/daixiang0/gci@latest
