# golangci-lint run

linters:
  enable-all: true
  disable:
    - exhaustivestruct # Deprecated
    - interfacer # Deprecated
    - scopelint # Deprecated
    - golint # Deprecated
    - maligned # Deprecated

    - cyclop
    - exhaustruct # extract code bload
    - forbidigo # forbids the use for fmt.Print(f|ln)
    - nlreturn # opinionated
    - nonamedreturns # opinionated
    - paralleltest # causes tests to randomly fail
    - tagliatelle # my interfere with external apis?
    - varnamelen # too many false-pos.
    - wrapcheck # wrapping 3rd party errors such as those from bolt are unnecessary
    - wsl # whitespace linter, slow, aggressive and opinionated

    # disabled in go v1.18
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - tparallel
    - unparam
    - wastedassign

# Fixes
# gofumpt -l -w <file> || <dir>/*
# gci -w <dir>/*
