# golangci-lint run

linters:
  enable-all: true
  disable:
    # deprecated 
    - deadcode
    - exhaustivestruct
    - ifshort
    - interfacer
    - scopelint
    - golint
    - maligned
    - nosnakecase
    - structcheck
    - varcheck

    # disabled
    - cyclop          # disabled for performance
    - exhaustruct     # conflicts with the cobra pkg
    - nlreturn        # opinionated
    - tagliatelle     # naming suggestions interfere with external APIs
    - varnamelen      # way too many false-positives
    - wrapcheck       # wrapping 3rd party errors is unnecessary
    - wsl             # whitespace linter, slow, aggressive and opinionated

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 13