# golangci-lint run

linters:
  enable-all: true
  disable:
    # deprecated
    - deadcode
    - exhaustivestruct
    - ifshort
    - interfacer
    - scopelint
    - golint
    - maligned
    - nosnakecase
    - structcheck
    - varcheck

    # disabled
    - cyclop
    - exhaustruct     # extract code bload
    - nlreturn        # opinionated
    - paralleltest    # causes tests to randomly fail
    - tagliatelle     # naming suggestions interfere with external APIs
    - varnamelen      # too many false-pos.
    - wrapcheck       # wrapping 3rd party errors is unnecessary
    - wsl             # whitespace linter, slow, aggressive and opinionated
    - musttag         # causes a false-pos with the std lib?

    # generics
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
