# SQLBoiler configuration file
# To rebuild run: `go generate` in the root of this repository.

# Target directory.
output = "pkg/models/psql" 

# This should always be kept to true.
wipe = true

# Add generation for global variants.
add-global-variants = false

# Add generation for panic variants.
add-panic-variants = false

# Disable the before and after query hook models.
no-hooks = true

# Disable generated go test files.
no-tests = false

# Postgres database connection.
[psql]
schema = "public"
dbname = "defacto2-ps"
host = "localhost"
port = 5432
user = "root"
pass = "example"
sslmode = "disable"

[auto-columns]
created = "createdat"
updated = "updatedat"
deleted = "deletedat"