// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testGroupnames(t *testing.T) {
	t.Parallel()

	query := Groupnames()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testGroupnamesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Groupnames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGroupnamesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Groupnames().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Groupnames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGroupnamesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GroupnameSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Groupnames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGroupnamesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := GroupnameExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Groupname exists: %s", err)
	}
	if !e {
		t.Errorf("Expected GroupnameExists to return true, but got false.")
	}
}

func testGroupnamesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	groupnameFound, err := FindGroupname(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if groupnameFound == nil {
		t.Error("want a record, got nil")
	}
}

func testGroupnamesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Groupnames().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testGroupnamesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Groupnames().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testGroupnamesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	groupnameOne := &Groupname{}
	groupnameTwo := &Groupname{}
	if err = randomize.Struct(seed, groupnameOne, groupnameDBTypes, false, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}
	if err = randomize.Struct(seed, groupnameTwo, groupnameDBTypes, false, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = groupnameOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = groupnameTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Groupnames().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testGroupnamesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	groupnameOne := &Groupname{}
	groupnameTwo := &Groupname{}
	if err = randomize.Struct(seed, groupnameOne, groupnameDBTypes, false, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}
	if err = randomize.Struct(seed, groupnameTwo, groupnameDBTypes, false, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = groupnameOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = groupnameTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Groupnames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testGroupnamesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Groupnames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGroupnamesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(groupnameColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Groupnames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGroupnamesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGroupnamesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GroupnameSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGroupnamesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Groupnames().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	groupnameDBTypes = map[string]string{`ID`: `smallint`, `Pubname`: `varchar`, `Initialisms`: `varchar`}
	_                = bytes.MinRead
)

func testGroupnamesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(groupnamePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(groupnameAllColumns) == len(groupnamePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Groupnames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnamePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testGroupnamesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(groupnameAllColumns) == len(groupnamePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Groupname{}
	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnameColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Groupnames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, groupnameDBTypes, true, groupnamePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(groupnameAllColumns, groupnamePrimaryKeyColumns) {
		fields = groupnameAllColumns
	} else {
		fields = strmangle.SetComplement(
			groupnameAllColumns,
			groupnamePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := GroupnameSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testGroupnamesUpsert(t *testing.T) {
	t.Parallel()

	if len(groupnameAllColumns) == len(groupnamePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLGroupnameUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Groupname{}
	if err = randomize.Struct(seed, &o, groupnameDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Groupname: %s", err)
	}

	count, err := Groupnames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, groupnameDBTypes, false, groupnamePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Groupname struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Groupname: %s", err)
	}

	count, err = Groupnames().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
