package cmd

// Code generated by go generate; ignore.

// Build and version information
type Build struct {
	// Commit git SHA
	Commit string
	// Date in RFC3339
	Date string
	// Version of Defacto2
	Version string
}

// B holds the build and version information.
var B = Build{
	Commit:  "n/a",
	Date:    "2020-08-04T09:48:05+10:00",
	Version: "1.1.3",
}
