package version

// Code generated by go generate; ignore.
// See /lib/root.go for the version flag.

// Build and version information
type Build struct {
	// Commit Git SHA
	Commit string
	// Date in RFC3339
	Date string
	// Version of Defacto2
	Version string
}

// B holds the build and version information.
var B = Build{
	Commit:  "n/a",
	Date:    "2020-08-05T16:51:36+10:00",
	Version: "1.1.3",
}
